name: arbormed
packages:
  - apps/student_app
  - packages/*

ignore:
  - _legacy/**

scripts:
  analyze:
    run: |
      melos exec -c 1 -- "flutter analyze"
    description: Run `flutter analyze` in all packages.

  test:
    run: |
      melos exec -c 1 -- "flutter test"
    description: Run `flutter test` in all packages.

  test:all:
    run: |
      melos exec -c 1 -- "flutter test"
    description: Run all tests across all feature packages.

  analyze:all:
    run: |
      melos exec -c 1 -- "flutter analyze"
    description: Analyze all packages.
