import 'shop_item.dart';

/// 🛒 MVP Catalog: Hardcoded items matching the new 3D/Layered assets
class ShopCatalog {
  static final List<ShopItem> items = [
    // 🏠 ROOMS
    ShopItem(
      id: 100,
      name: 'Cozy Morning',
      type: 'room',
      slotType: 'room',
      price: 0,
      assetPath: 'assets/images/room/room_0.webp',
      description: 'A bright, sun-filled room perfect for early risers.',
      isOwned: false,
    ),
    ShopItem(
      id: 101,
      name: 'Midnight Study',
      type: 'room',
      slotType: 'room',
      price: 500,
      assetPath: 'assets/images/room/room_1.webp',
      description: 'Deep calm tones for focused night sessions.',
      isOwned: false,
    ),

    // 🪑 FURNITURE (Desks)
    ShopItem(
      id: 200,
      name: 'Oak Starter Desk',
      type: 'furniture',
      slotType: 'desk',
      price: 100,
      assetPath: 'assets/images/furniture/desk_0.webp',
      description: 'Sturdy and reliable.',
      isOwned: false,
    ),
    ShopItem(
      id: 201,
      name: 'Minimalist White',
      type: 'furniture',
      slotType: 'desk',
      price: 100,
      assetPath: 'assets/images/furniture/desk_1.webp',
      description: 'Clean lines for a clear mind.',
      isOwned: false,
    ),
    ShopItem(
      id: 202,
      name: 'Mahogany Executive',
      type: 'furniture',
      slotType: 'desk',
      price: 100,
      assetPath: 'assets/images/furniture/desk_2.webp',
      description: 'Serious business.',
      isOwned: false,
    ),
    ShopItem(
      id: 203,
      name: 'Gamer Station',
      type: 'furniture',
      slotType: 'desk',
      price: 100,
      assetPath: 'assets/images/furniture/desk_3.webp',
      description: 'RGB increases performance by 10%.',
      isOwned: false,
    ),

    // 🖥️ DESK DECOR (Computers)
    ShopItem(
      id: 300,
      name: 'Modern Workstation',
      type: 'furniture',
      slotType: 'desk_decor',
      price: 75,
      assetPath: 'assets/images/furniture/computer_0.webp',
      description: 'A high-performance system for medical data.',
      isOwned: false,
    ),
    ShopItem(
      id: 301,
      name: 'Advanced Terminal',
      type: 'furniture',
      slotType: 'desk_decor',
      price: 75,
      assetPath: 'assets/images/furniture/computer_1.webp',
      description: 'Professional-grade processing power.',
      isOwned: false,
    ),
    ShopItem(
      id: 302,
      name: 'Dual Monitor Setup',
      type: 'furniture',
      slotType: 'desk_decor',
      price: 125,
      assetPath: 'assets/images/furniture/computer_2.webp',
      description: 'Multitasking enabled.',
      isOwned: false,
    ),

    // 🏥 CLINICAL (Gurneys)
    ShopItem(
      id: 400,
      name: 'Basic Exam Bed',
      type: 'furniture',
      slotType: 'exam_table',
      price: 150,
      assetPath: 'assets/images/furniture/gurney_0.webp',
      description: 'Standard issue.',
      isOwned: false,
    ),
    ShopItem(
      id: 401,
      name: 'Advanced Gurney',
      type: 'furniture',
      slotType: 'exam_table',
      price: 150,
      assetPath: 'assets/images/furniture/gurney_1.webp',
      description: 'With hydraulic lift support.',
      isOwned: false,
    ),
    ShopItem(
      id: 402,
      name: 'Surgical Table',
      type: 'furniture',
      slotType: 'exam_table',
      price: 250,
      assetPath: 'assets/images/furniture/gurney_2.webp',
      description: 'Precision adjustment capability.',
      isOwned: false,
    ),
    ShopItem(
      id: 403,
      name: 'Recovery Bed',
      type: 'furniture',
      slotType: 'exam_table',
      price: 200,
      assetPath: 'assets/images/furniture/gurney_3.webp',
      description: 'Comfortable for post-op.',
      isOwned: false,
    ),

    // 🎨 DECOR (Wall)
    ShopItem(
      id: 500,
      name: 'Geometric Wall Art',
      type: 'furniture',
      slotType: 'wall_decor',
      price: 75,
      assetPath: 'assets/images/furniture/wall_decor.webp',
      description: 'Adds a splash of color to the clinic.',
      isOwned: false,
    ),

    // 🪟 WINDOWS
    ShopItem(
      id: 600,
      name: 'Sunny Window',
      type: 'furniture',
      slotType: 'window',
      price: 200,
      assetPath: 'assets/images/furniture/window.webp',
      description: 'Let the sunshine in.',
      isOwned: false,
    ),

    // 📦 CORNER CABINETS
    ShopItem(
      id: 700,
      name: 'Basic File Cabinet',
      type: 'furniture',
      slotType: 'corner_cabinet',
      price: 80,
      assetPath: 'assets/images/furniture/cornercabinet_0.webp',
      description: 'Essential storage.',
      isOwned: false,
    ),
    ShopItem(
      id: 701,
      name: 'Tall Shelf',
      type: 'furniture',
      slotType: 'corner_cabinet',
      price: 90,
      assetPath: 'assets/images/furniture/cornercabinet_1.webp',
      description: 'Maximize vertical space.',
      isOwned: false,
    ),
    ShopItem(
      id: 702,
      name: 'Glass Display',
      type: 'furniture',
      slotType: 'corner_cabinet',
      price: 110,
      assetPath: 'assets/images/furniture/cornercabinet_2.webp',
      description: 'Showcase your achievements.',
      isOwned: false,
    ),
    ShopItem(
      id: 703,
      name: 'Medical Supply Cabinet',
      type: 'furniture',
      slotType: 'corner_cabinet',
      price: 100,
      assetPath: 'assets/images/furniture/cornercabinet_3.webp',
      description: 'Keep supplies organized.',
      isOwned: false,
    ),

    // 🧶 RUGS
    ShopItem(
      id: 800,
      name: 'Welcome Mat',
      type: 'furniture',
      slotType: 'rug',
      price: 30,
      assetPath: 'assets/images/furniture/rug_0.webp',
      description: 'A warm welcome.',
      isOwned: false,
    ),
    ShopItem(
      id: 801,
      name: 'Persian Rug',
      type: 'furniture',
      slotType: 'rug',
      price: 150,
      assetPath: 'assets/images/furniture/rug_1.webp',
      description: 'Adds elegance.',
      isOwned: false,
    ),
    ShopItem(
      id: 802,
      name: 'Modern Geometric Rug',
      type: 'furniture',
      slotType: 'rug',
      price: 80,
      assetPath: 'assets/images/furniture/rug_2.webp',
      description: 'Contemporary style.',
      isOwned: false,
    ),


  ];
}
