name: feature_auth
description: Auth feature package for ArborMed.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  arbormed_core:
    path: ../core
  core_interop:
    path: ../core_interop
  provider: ^6.0.5
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  firebase_auth: ^5.5.0 # Latest standard
  google_sign_in: ^6.2.1
  get_it: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
