name: feature_auth
description: Authentication feature for ArborMed.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  arbormed_core:
    path: ../core
  google_fonts: ^6.3.3
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.3
  dio: ^5.4.3+1
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
