// Mocks generated by Mockito 5.4.6 from annotations
// in arbor_med/test/services/question_cache_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:arbor_med/services/api_service.dart' as _i2;
import 'package:image_picker/image_picker.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onTokenRefreshed(dynamic Function(String)? value) => super.noSuchMethod(
        Invocation.setter(
          #onTokenRefreshed,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLanguage(String? lang) => super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [lang],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setToken(
    String? token, {
    String? refreshToken,
    int? userId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setToken,
          [token],
          {
            #refreshToken: refreshToken,
            #userId: userId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<int?> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);

  @override
  _i3.Future<dynamic> post(
    String? endpoint,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            endpoint,
            data,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> put(
    String? endpoint,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            endpoint,
            data,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> get(String? endpoint) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> getBytes(String? endpoint) => (super.noSuchMethod(
        Invocation.method(
          #getBytes,
          [endpoint],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<void> submitReport(
    int? questionId,
    String? reason,
    String? description,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitReport,
          [
            questionId,
            reason,
            description,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<dynamic> delete(String? endpoint) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> postMultipart(
    String? endpoint, {
    required List<int>? bytes,
    required String? filename,
    String? fieldName = 'file',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postMultipart,
          [endpoint],
          {
            #bytes: bytes,
            #filename: filename,
            #fieldName: fieldName,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<String?> uploadImage(
    _i4.XFile? file, {
    String? folder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [file],
          {#folder: folder},
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
}
