name: feature_game
description: Game and Room features for ArborMed.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  arbormed_core:
    path: ../core
  google_fonts: ^6.3.3
  provider: ^6.0.5
  logger: ^2.3.0
  feature_social:
    path: ../feature_social
  feature_quiz:
    path: ../feature_quiz

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
