// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBacBODPU3wtQ5_LkO7kwfmfWLMeNT1avY',
    appId: '1:314214605741:web:ad00be378e7b2ebfe1b724',
    messagingSenderId: '314214605741',
    projectId: 'medbuddy-e77e5',
    authDomain: 'medbuddy-e77e5.firebaseapp.com',
    storageBucket: 'medbuddy-e77e5.firebasestorage.app',
    measurementId: 'G-D58DG60JRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5bBHkH3pMc8xzQTniwN4Z5xSOyJoPQCI',
    appId: '1:314214605741:android:0231cdb60d507e6be1b724',
    messagingSenderId: '314214605741',
    projectId: 'medbuddy-e77e5',
    storageBucket: 'medbuddy-e77e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsxxLT_y0rPHmeCF6Xup02eLBmY42V7Lg',
    appId: '1:314214605741:ios:2c98ed5d8843994fe1b724',
    messagingSenderId: '314214605741',
    projectId: 'medbuddy-e77e5',
    storageBucket: 'medbuddy-e77e5.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsxxLT_y0rPHmeCF6Xup02eLBmY42V7Lg',
    appId: '1:314214605741:ios:2c98ed5d8843994fe1b724',
    messagingSenderId: '314214605741',
    projectId: 'medbuddy-e77e5',
    storageBucket: 'medbuddy-e77e5.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBacBODPU3wtQ5_LkO7kwfmfWLMeNT1avY',
    appId: '1:314214605741:web:37c7dc51d3b31b82e1b724',
    messagingSenderId: '314214605741',
    projectId: 'medbuddy-e77e5',
    authDomain: 'medbuddy-e77e5.firebaseapp.com',
    storageBucket: 'medbuddy-e77e5.firebasestorage.app',
    measurementId: 'G-HNRJL0GGMW',
  );
}
