// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe193dkgDJHyXitLQryMoTdbWSm3wfC_k',
    appId: '1:325448103902:web:29b193b67378867f044f4f',
    messagingSenderId: '325448103902',
    projectId: 'arbormed-b72fc',
    authDomain: 'arbormed-b72fc.firebaseapp.com',
    storageBucket: 'arbormed-b72fc.firebasestorage.app',
    measurementId: 'G-XVRCRF7FW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRzmhnC9RVM_ELHthxvZDJ1vWagz_y7xY',
    appId: '1:325448103902:android:ba608eca89816551044f4f',
    messagingSenderId: '325448103902',
    projectId: 'arbormed-b72fc',
    storageBucket: 'arbormed-b72fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwrAWs5q_s4zkiRUoPTn_EJSduGGVhGSE',
    appId: '1:325448103902:ios:1ca6b1a1d45e7ec0044f4f',
    messagingSenderId: '325448103902',
    projectId: 'arbormed-b72fc',
    storageBucket: 'arbormed-b72fc.firebasestorage.app',
    iosBundleId: 'com.example.arbormed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwrAWs5q_s4zkiRUoPTn_EJSduGGVhGSE',
    appId: '1:325448103902:ios:e5099214b78dfdd6044f4f',
    messagingSenderId: '325448103902',
    projectId: 'arbormed-b72fc',
    storageBucket: 'arbormed-b72fc.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe193dkgDJHyXitLQryMoTdbWSm3wfC_k',
    appId: '1:325448103902:web:04d98c965e3ea10d044f4f',
    messagingSenderId: '325448103902',
    projectId: 'arbormed-b72fc',
    authDomain: 'arbormed-b72fc.firebaseapp.com',
    storageBucket: 'arbormed-b72fc.firebasestorage.app',
    measurementId: 'G-HME4CZ98QY',
  );

}