// AUTO-GENERATED by tools/maintain_shop.py
// DO NOT EDIT MANUALLY. Run the tool to update.

import 'shop_item.dart';

class GeneratedShopCatalog {
  static final List<ShopItem> items = [
    ShopItem(
      id: 100,
      name: 'Cozy Morning',
      type: 'room',
      slotType: 'room',
      price: 0,
      assetPath: 'assets/images/room/room_0.webp',
      description: 'Cozy Morning', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 200,
      name: 'Oak Starter Desk',
      type: 'furniture',
      slotType: 'desk',
      price: 150,
      assetPath: 'assets/images/furniture/desk_0.webp',
      description: 'Oak Starter Desk', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 201,
      name: 'Minimalist White',
      type: 'furniture',
      slotType: 'desk',
      price: 150,
      assetPath: 'assets/images/furniture/desk_1.webp',
      description: 'Minimalist White', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 202,
      name: 'Mahogany Executive',
      type: 'furniture',
      slotType: 'desk',
      price: 200,
      assetPath: 'assets/images/furniture/desk_2.webp',
      description: 'Mahogany Executive', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 203,
      name: 'Gamer Station',
      type: 'furniture',
      slotType: 'desk',
      price: 200,
      assetPath: 'assets/images/furniture/desk_3.webp',
      description: 'Gamer Station', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 204,
      name: 'Vintage Medical Desk',
      type: 'furniture',
      slotType: 'desk',
      price: 250,
      assetPath: 'assets/images/furniture/desk_4.webp',
      description: 'Vintage Medical Desk', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 250,
      name: 'Modern Workstation',
      type: 'furniture',
      slotType: 'desk_decor',
      price: 100,
      assetPath: 'assets/images/furniture/computer_0.webp',
      description: 'Modern Workstation', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 301,
      name: 'Advanced Terminal',
      type: 'furniture',
      slotType: 'desk_decor',
      price: 100,
      assetPath: 'assets/images/furniture/computer_1.webp',
      description: 'Advanced Terminal', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 302,
      name: 'Dual Monitor Setup',
      type: 'furniture',
      slotType: 'desk_decor',
      price: 100,
      assetPath: 'assets/images/furniture/computer_2.webp',
      description: 'Dual Monitor Setup', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 251,
      name: 'Heavy Duty Desktop',
      type: 'furniture',
      slotType: 'desk_decor',
      price: 120,
      assetPath: 'assets/images/furniture/computer_3.webp',
      description: 'Heavy Duty Desktop', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 400,
      name: 'Basic Exam Bed',
      type: 'furniture',
      slotType: 'exam_table',
      price: 200,
      assetPath: 'assets/images/furniture/gurney_0.webp',
      description: 'Basic Exam Bed', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 401,
      name: 'Advanced Gurney',
      type: 'furniture',
      slotType: 'exam_table',
      price: 200,
      assetPath: 'assets/images/furniture/gurney_1.webp',
      description: 'Advanced Gurney', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 402,
      name: 'Surgical Table',
      type: 'furniture',
      slotType: 'exam_table',
      price: 250,
      assetPath: 'assets/images/furniture/gurney_2.webp',
      description: 'Surgical Table', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 403,
      name: 'Recovery Bed',
      type: 'furniture',
      slotType: 'exam_table',
      price: 300,
      assetPath: 'assets/images/furniture/gurney_3.webp',
      description: 'Recovery Bed', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 700,
      name: 'Basic File Cabinet',
      type: 'furniture',
      slotType: 'corner_cabinet',
      price: 250,
      assetPath: 'assets/images/furniture/cornercabinet_0.webp',
      description: 'Basic File Cabinet', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 701,
      name: 'Tall Shelf',
      type: 'furniture',
      slotType: 'corner_cabinet',
      price: 250,
      assetPath: 'assets/images/furniture/cornercabinet_1.webp',
      description: 'Tall Shelf', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 702,
      name: 'Glass Display',
      type: 'furniture',
      slotType: 'corner_cabinet',
      price: 250,
      assetPath: 'assets/images/furniture/cornercabinet_2.webp',
      description: 'Glass Display', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 703,
      name: 'Medical Supply Cabinet',
      type: 'furniture',
      slotType: 'corner_cabinet',
      price: 250,
      assetPath: 'assets/images/furniture/cornercabinet_3.webp',
      description: 'Medical Supply Cabinet', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 704,
      name: 'Antique Curio',
      type: 'furniture',
      slotType: 'corner_cabinet',
      price: 300,
      assetPath: 'assets/images/furniture/cornercabinet_4.webp',
      description: 'Antique Curio', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 800,
      name: 'Welcome Mat',
      type: 'furniture',
      slotType: 'rug',
      price: 150,
      assetPath: 'assets/images/furniture/rug_0.webp',
      description: 'Welcome Mat', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 801,
      name: 'Persian Rug',
      type: 'furniture',
      slotType: 'rug',
      price: 150,
      assetPath: 'assets/images/furniture/rug_1.webp',
      description: 'Persian Rug', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 802,
      name: 'Modern Geometric Rug',
      type: 'furniture',
      slotType: 'rug',
      price: 150,
      assetPath: 'assets/images/furniture/rug_2.webp',
      description: 'Modern Geometric Rug', // Placeholder
      isOwned: false,
    ),
    ShopItem(
      id: 803,
      name: 'Zen Stone Rug',
      type: 'furniture',
      slotType: 'rug',
      price: 200,
      assetPath: 'assets/images/furniture/rug_3.webp',
      description: 'Zen Stone Rug', // Placeholder
      isOwned: false,
    ),
  ];
}
